// Mocks generated by Mockito 5.3.3-dev from annotations
// in trip_planner_aquamarine/test/orientation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:geomag/geomag.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGeoMagResult_0 extends _i1.SmartFake implements _i2.GeoMagResult {
  _FakeGeoMagResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GeoMag].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoMag extends _i1.Mock implements _i2.GeoMag {
  @override
  _i2.GeoMagResult calculate(
    double? lat,
    double? lng, [
    double? heightFeet = 0.0,
    DateTime? date,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculate,
          [
            lat,
            lng,
            heightFeet,
            date,
          ],
        ),
        returnValue: _FakeGeoMagResult_0(
          this,
          Invocation.method(
            #calculate,
            [
              lat,
              lng,
              heightFeet,
              date,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeGeoMagResult_0(
          this,
          Invocation.method(
            #calculate,
            [
              lat,
              lng,
              heightFeet,
              date,
            ],
          ),
        ),
      ) as _i2.GeoMagResult);
}
