// Mocks generated by Mockito 5.3.2 from annotations
// in trip_planner_aquamarine/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:joda/time.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:trip_planner_aquamarine/providers/trip_planner_client.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTripPlannerEndpoints_0 extends _i1.SmartFake
    implements _i2.TripPlannerEndpoints {
  _FakeTripPlannerEndpoints_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimeZone_1 extends _i1.SmartFake implements _i3.TimeZone {
  _FakeTimeZone_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_2 extends _i1.SmartFake implements Uri {
  _FakeUri_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TripPlannerClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripPlannerClient extends _i1.Mock implements _i2.TripPlannerClient {
  @override
  _i2.TripPlannerEndpoints get endpoints => (super.noSuchMethod(
        Invocation.getter(#endpoints),
        returnValue: _FakeTripPlannerEndpoints_0(
          this,
          Invocation.getter(#endpoints),
        ),
        returnValueForMissingStub: _FakeTripPlannerEndpoints_0(
          this,
          Invocation.getter(#endpoints),
        ),
      ) as _i2.TripPlannerEndpoints);
  @override
  _i3.TimeZone get timeZone => (super.noSuchMethod(
        Invocation.getter(#timeZone),
        returnValue: _FakeTimeZone_1(
          this,
          Invocation.getter(#timeZone),
        ),
        returnValueForMissingStub: _FakeTimeZone_1(
          this,
          Invocation.getter(#timeZone),
        ),
      ) as _i3.TimeZone);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<Set<_i2.Station>> getDatapoints() => (super.noSuchMethod(
        Invocation.method(
          #getDatapoints,
          [],
        ),
        returnValue: _i4.Future<Set<_i2.Station>>.value(<_i2.Station>{}),
        returnValueForMissingStub:
            _i4.Future<Set<_i2.Station>>.value(<_i2.Station>{}),
      ) as _i4.Future<Set<_i2.Station>>);
  @override
  Uri tideGraphUrl(
    _i2.Station? station,
    int? days,
    int? width,
    int? height,
    _i3.Date? t,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #tideGraphUrl,
          [
            station,
            days,
            width,
            height,
            t,
          ],
        ),
        returnValue: _FakeUri_2(
          this,
          Invocation.method(
            #tideGraphUrl,
            [
              station,
              days,
              width,
              height,
              t,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeUri_2(
          this,
          Invocation.method(
            #tideGraphUrl,
            [
              station,
              days,
              width,
              height,
              t,
            ],
          ),
        ),
      ) as Uri);
}
