// Mocks generated by Mockito 5.3.2 from annotations
// in trip_planner_aquamarine/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:http/http.dart' as _i2;
import 'package:joda/time.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:trip_planner_aquamarine/providers/trip_planner_client.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTripPlannerEndpoints_1 extends _i1.SmartFake
    implements _i3.TripPlannerEndpoints {
  _FakeTripPlannerEndpoints_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TripPlannerHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripPlannerHttpClient extends _i1.Mock
    implements _i3.TripPlannerHttpClient {
  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);
  @override
  _i3.TripPlannerEndpoints get endpoints => (super.noSuchMethod(
        Invocation.getter(#endpoints),
        returnValue: _FakeTripPlannerEndpoints_1(
          this,
          Invocation.getter(#endpoints),
        ),
        returnValueForMissingStub: _FakeTripPlannerEndpoints_1(
          this,
          Invocation.getter(#endpoints),
        ),
      ) as _i3.TripPlannerEndpoints);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<Map<_i3.StationId, _i3.Station>> getDatapoints() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDatapoints,
          [],
        ),
        returnValue: _i4.Future<Map<_i3.StationId, _i3.Station>>.value(
            <_i3.StationId, _i3.Station>{}),
        returnValueForMissingStub:
            _i4.Future<Map<_i3.StationId, _i3.Station>>.value(
                <_i3.StationId, _i3.Station>{}),
      ) as _i4.Future<Map<_i3.StationId, _i3.Station>>);
  @override
  _i4.Future<_i5.Uint8List> getTideGraph(
    _i3.Station? station,
    int? days,
    int? width,
    int? height,
    _i6.Date? begin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTideGraph,
          [
            station,
            days,
            width,
            height,
            begin,
          ],
        ),
        returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
        returnValueForMissingStub:
            _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i4.Future<_i5.Uint8List>);
}
