name: aquamarine_server_interface
publish_to: none
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  equatable: ^2.0.5
  http: ^0.13.5
  latlng:
    path: ../../latlng
  vector_math: ^2.1.4

dev_dependencies:
  convert: ^3.1.1
  lints: ^2.0.0
  test: ^1.21.7