name: aquamarine_server_interface
publish_to: none
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  equatable: ^2.0.5
  http: ^0.13.5
  latlng:
    path: ../../latlng
  vector_math: ^2.1.4

dev_dependencies:
  aquamarine_lints:
    path: ../../lints
  test_data:
    path: ../../test_data
    
  convert: ^3.1.1
  test: ^1.21.7