name: test_data
publish_to: none
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  file_picker: ^5.2.4
  trip_planner_aquamarine:
    path: ../app

dev_dependencies:
  aquamarine_lints:
    path: ../lints