name: aquamarine_server
publish_to: none
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  aquamarine_server_interface:
    path: ifc
  aquamarine_util:
    path: ../util
  async: ^2.10.0
  clock: ^1.1.1
  convert: ^3.1.1
  crypto: ^3.0.2
  equatable: ^2.0.5
  file:
    git:
      url: https://github.com/AsturaPhoenix/file.dart.git
      path: packages/file
      ref: 1ffc9bd2dfd4a9be290f6201c8918b30c02909b6
  http: ^0.13.5
  latlng:
    path: ../latlng
  logging: ^1.2.0
  mutex: ^3.0.1
  path: ^1.8.2
  shelf: ^1.4.0
  shelf_router: ^1.1.3

dependency_overrides:
  file:
    git:
      url: https://github.com/AsturaPhoenix/file.dart.git
      path: packages/file
      ref: 1ffc9bd2dfd4a9be290f6201c8918b30c02909b6

dev_dependencies:
  build_runner: ^2.3.3
  fake_async: ^1.3.1
  lints: ^2.0.0
  meta: ^1.9.0
  mockito: ^5.4.0
  test: ^1.21.7