// Mocks generated by Mockito 5.4.0 from annotations
// in aquamarine_server/test/aquamarine_server_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i6;

import 'package:aquamarine_server/ofs_client.dart' as _i3;
import 'package:aquamarine_server/types.dart' as _i5;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OfsClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfsClient extends _i1.Mock implements _i3.OfsClient {
  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);
  @override
  _i4.Future<_i2.ByteStream?> fetchResource(
    _i5.SimulationTime? s,
    List<String>? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchResource,
          [
            s,
            query,
          ],
        ),
        returnValue: _i4.Future<_i2.ByteStream?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.ByteStream?>.value(),
      ) as _i4.Future<_i2.ByteStream?>);
  @override
  _i4.Future<_i4.Stream<_i6.Uint8List>?> fetchLatLng(_i5.SimulationTime? s) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLatLng,
          [s],
        ),
        returnValue: _i4.Future<_i4.Stream<_i6.Uint8List>?>.value(),
        returnValueForMissingStub:
            _i4.Future<_i4.Stream<_i6.Uint8List>?>.value(),
      ) as _i4.Future<_i4.Stream<_i6.Uint8List>?>);
  @override
  _i4.Future<_i3.OfsUvData?> fetchUv(_i5.SimulationTime? s) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUv,
          [s],
        ),
        returnValue: _i4.Future<_i3.OfsUvData?>.value(),
        returnValueForMissingStub: _i4.Future<_i3.OfsUvData?>.value(),
      ) as _i4.Future<_i3.OfsUvData?>);
}
