// Mocks generated by Mockito 5.4.2 from annotations
// in aquamarine_server/test/persistence_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:convert' as _i9;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i11;

import 'package:file/src/interface/directory.dart' as _i3;
import 'package:file/src/interface/file.dart' as _i4;
import 'package:file/src/interface/file_system.dart' as _i7;
import 'package:file/src/interface/file_system_entity.dart' as _i8;
import 'package:file/src/interface/link.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:path/path.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContext_0 extends _i1.SmartFake implements _i2.Context {
  _FakeContext_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDirectory_1 extends _i1.SmartFake implements _i3.Directory {
  _FakeDirectory_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_2 extends _i1.SmartFake implements _i4.File {
  _FakeFile_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLink_3 extends _i1.SmartFake implements _i5.Link {
  _FakeLink_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileStat_4 extends _i1.SmartFake implements _i6.FileStat {
  _FakeFileStat_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileSystemEntityType_5 extends _i1.SmartFake
    implements _i6.FileSystemEntityType {
  _FakeFileSystemEntityType_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileSystem_6 extends _i1.SmartFake implements _i7.FileSystem {
  _FakeFileSystem_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_7 extends _i1.SmartFake implements Uri {
  _FakeUri_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileSystemEntity_8 extends _i1.SmartFake
    implements _i8.FileSystemEntity {
  _FakeFileSystemEntity_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_9 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRandomAccessFile_10 extends _i1.SmartFake
    implements _i6.RandomAccessFile {
  _FakeRandomAccessFile_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSink_11 extends _i1.SmartFake implements _i6.IOSink {
  _FakeIOSink_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEncoding_12 extends _i1.SmartFake implements _i9.Encoding {
  _FakeEncoding_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FileSystem].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileSystem extends _i1.Mock implements _i7.FileSystem {
  @override
  _i2.Context get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _FakeContext_0(
          this,
          Invocation.getter(#path),
        ),
        returnValueForMissingStub: _FakeContext_0(
          this,
          Invocation.getter(#path),
        ),
      ) as _i2.Context);
  @override
  _i3.Directory get systemTempDirectory => (super.noSuchMethod(
        Invocation.getter(#systemTempDirectory),
        returnValue: _FakeDirectory_1(
          this,
          Invocation.getter(#systemTempDirectory),
        ),
        returnValueForMissingStub: _FakeDirectory_1(
          this,
          Invocation.getter(#systemTempDirectory),
        ),
      ) as _i3.Directory);
  @override
  _i3.Directory get currentDirectory => (super.noSuchMethod(
        Invocation.getter(#currentDirectory),
        returnValue: _FakeDirectory_1(
          this,
          Invocation.getter(#currentDirectory),
        ),
        returnValueForMissingStub: _FakeDirectory_1(
          this,
          Invocation.getter(#currentDirectory),
        ),
      ) as _i3.Directory);
  @override
  set currentDirectory(dynamic path) => super.noSuchMethod(
        Invocation.setter(
          #currentDirectory,
          path,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get isWatchSupported => (super.noSuchMethod(
        Invocation.getter(#isWatchSupported),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i3.Directory directory(dynamic path) => (super.noSuchMethod(
        Invocation.method(
          #directory,
          [path],
        ),
        returnValue: _FakeDirectory_1(
          this,
          Invocation.method(
            #directory,
            [path],
          ),
        ),
        returnValueForMissingStub: _FakeDirectory_1(
          this,
          Invocation.method(
            #directory,
            [path],
          ),
        ),
      ) as _i3.Directory);
  @override
  _i4.File file(dynamic path) => (super.noSuchMethod(
        Invocation.method(
          #file,
          [path],
        ),
        returnValue: _FakeFile_2(
          this,
          Invocation.method(
            #file,
            [path],
          ),
        ),
        returnValueForMissingStub: _FakeFile_2(
          this,
          Invocation.method(
            #file,
            [path],
          ),
        ),
      ) as _i4.File);
  @override
  _i5.Link link(dynamic path) => (super.noSuchMethod(
        Invocation.method(
          #link,
          [path],
        ),
        returnValue: _FakeLink_3(
          this,
          Invocation.method(
            #link,
            [path],
          ),
        ),
        returnValueForMissingStub: _FakeLink_3(
          this,
          Invocation.method(
            #link,
            [path],
          ),
        ),
      ) as _i5.Link);
  @override
  _i10.Future<_i6.FileStat> stat(String? path) => (super.noSuchMethod(
        Invocation.method(
          #stat,
          [path],
        ),
        returnValue: _i10.Future<_i6.FileStat>.value(_FakeFileStat_4(
          this,
          Invocation.method(
            #stat,
            [path],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i6.FileStat>.value(_FakeFileStat_4(
          this,
          Invocation.method(
            #stat,
            [path],
          ),
        )),
      ) as _i10.Future<_i6.FileStat>);
  @override
  _i6.FileStat statSync(String? path) => (super.noSuchMethod(
        Invocation.method(
          #statSync,
          [path],
        ),
        returnValue: _FakeFileStat_4(
          this,
          Invocation.method(
            #statSync,
            [path],
          ),
        ),
        returnValueForMissingStub: _FakeFileStat_4(
          this,
          Invocation.method(
            #statSync,
            [path],
          ),
        ),
      ) as _i6.FileStat);
  @override
  _i10.Future<bool> identical(
    String? path1,
    String? path2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #identical,
          [
            path1,
            path2,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  bool identicalSync(
    String? path1,
    String? path2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #identicalSync,
          [
            path1,
            path2,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i10.Future<_i6.FileSystemEntityType> type(
    String? path, {
    bool? followLinks = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #type,
          [path],
          {#followLinks: followLinks},
        ),
        returnValue: _i10.Future<_i6.FileSystemEntityType>.value(
            _FakeFileSystemEntityType_5(
          this,
          Invocation.method(
            #type,
            [path],
            {#followLinks: followLinks},
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i6.FileSystemEntityType>.value(
            _FakeFileSystemEntityType_5(
          this,
          Invocation.method(
            #type,
            [path],
            {#followLinks: followLinks},
          ),
        )),
      ) as _i10.Future<_i6.FileSystemEntityType>);
  @override
  _i6.FileSystemEntityType typeSync(
    String? path, {
    bool? followLinks = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #typeSync,
          [path],
          {#followLinks: followLinks},
        ),
        returnValue: _FakeFileSystemEntityType_5(
          this,
          Invocation.method(
            #typeSync,
            [path],
            {#followLinks: followLinks},
          ),
        ),
        returnValueForMissingStub: _FakeFileSystemEntityType_5(
          this,
          Invocation.method(
            #typeSync,
            [path],
            {#followLinks: followLinks},
          ),
        ),
      ) as _i6.FileSystemEntityType);
  @override
  _i10.Future<bool> isFile(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isFile,
          [path],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  bool isFileSync(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isFileSync,
          [path],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i10.Future<bool> isDirectory(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isDirectory,
          [path],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  bool isDirectorySync(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isDirectorySync,
          [path],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i10.Future<bool> isLink(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isLink,
          [path],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  bool isLinkSync(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isLinkSync,
          [path],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  String getPath(dynamic path) => (super.noSuchMethod(
        Invocation.method(
          #getPath,
          [path],
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i4.File {
  @override
  _i4.File get absolute => (super.noSuchMethod(
        Invocation.getter(#absolute),
        returnValue: _FakeFile_2(
          this,
          Invocation.getter(#absolute),
        ),
        returnValueForMissingStub: _FakeFile_2(
          this,
          Invocation.getter(#absolute),
        ),
      ) as _i4.File);
  @override
  _i7.FileSystem get fileSystem => (super.noSuchMethod(
        Invocation.getter(#fileSystem),
        returnValue: _FakeFileSystem_6(
          this,
          Invocation.getter(#fileSystem),
        ),
        returnValueForMissingStub: _FakeFileSystem_6(
          this,
          Invocation.getter(#fileSystem),
        ),
      ) as _i7.FileSystem);
  @override
  String get basename => (super.noSuchMethod(
        Invocation.getter(#basename),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get dirname => (super.noSuchMethod(
        Invocation.getter(#dirname),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i3.Directory get parent => (super.noSuchMethod(
        Invocation.getter(#parent),
        returnValue: _FakeDirectory_1(
          this,
          Invocation.getter(#parent),
        ),
        returnValueForMissingStub: _FakeDirectory_1(
          this,
          Invocation.getter(#parent),
        ),
      ) as _i3.Directory);
  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  Uri get uri => (super.noSuchMethod(
        Invocation.getter(#uri),
        returnValue: _FakeUri_7(
          this,
          Invocation.getter(#uri),
        ),
        returnValueForMissingStub: _FakeUri_7(
          this,
          Invocation.getter(#uri),
        ),
      ) as Uri);
  @override
  bool get isAbsolute => (super.noSuchMethod(
        Invocation.getter(#isAbsolute),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i10.Future<_i4.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #recursive: recursive,
            #exclusive: exclusive,
          },
        ),
        returnValue: _i10.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #create,
            [],
            {
              #recursive: recursive,
              #exclusive: exclusive,
            },
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #create,
            [],
            {
              #recursive: recursive,
              #exclusive: exclusive,
            },
          ),
        )),
      ) as _i10.Future<_i4.File>);
  @override
  _i10.Future<_i4.File> rename(String? newPath) => (super.noSuchMethod(
        Invocation.method(
          #rename,
          [newPath],
        ),
        returnValue: _i10.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #rename,
            [newPath],
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #rename,
            [newPath],
          ),
        )),
      ) as _i10.Future<_i4.File>);
  @override
  _i4.File renameSync(String? newPath) => (super.noSuchMethod(
        Invocation.method(
          #renameSync,
          [newPath],
        ),
        returnValue: _FakeFile_2(
          this,
          Invocation.method(
            #renameSync,
            [newPath],
          ),
        ),
        returnValueForMissingStub: _FakeFile_2(
          this,
          Invocation.method(
            #renameSync,
            [newPath],
          ),
        ),
      ) as _i4.File);
  @override
  _i10.Future<_i4.File> copy(String? newPath) => (super.noSuchMethod(
        Invocation.method(
          #copy,
          [newPath],
        ),
        returnValue: _i10.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #copy,
            [newPath],
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #copy,
            [newPath],
          ),
        )),
      ) as _i10.Future<_i4.File>);
  @override
  _i4.File copySync(String? newPath) => (super.noSuchMethod(
        Invocation.method(
          #copySync,
          [newPath],
        ),
        returnValue: _FakeFile_2(
          this,
          Invocation.method(
            #copySync,
            [newPath],
          ),
        ),
        returnValueForMissingStub: _FakeFile_2(
          this,
          Invocation.method(
            #copySync,
            [newPath],
          ),
        ),
      ) as _i4.File);
  @override
  _i10.Future<_i4.File> writeAsBytes(
    List<int>? bytes, {
    _i6.FileMode? mode = _i6.FileMode.write,
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAsBytes,
          [bytes],
          {
            #mode: mode,
            #flush: flush,
          },
        ),
        returnValue: _i10.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #writeAsBytes,
            [bytes],
            {
              #mode: mode,
              #flush: flush,
            },
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #writeAsBytes,
            [bytes],
            {
              #mode: mode,
              #flush: flush,
            },
          ),
        )),
      ) as _i10.Future<_i4.File>);
  @override
  _i10.Future<_i4.File> writeAsString(
    String? contents, {
    _i6.FileMode? mode = _i6.FileMode.write,
    _i9.Encoding? encoding = const _i9.Utf8Codec(),
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAsString,
          [contents],
          {
            #mode: mode,
            #encoding: encoding,
            #flush: flush,
          },
        ),
        returnValue: _i10.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #writeAsString,
            [contents],
            {
              #mode: mode,
              #encoding: encoding,
              #flush: flush,
            },
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #writeAsString,
            [contents],
            {
              #mode: mode,
              #encoding: encoding,
              #flush: flush,
            },
          ),
        )),
      ) as _i10.Future<_i4.File>);
  @override
  _i10.Future<_i8.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {#recursive: recursive},
        ),
        returnValue:
            _i10.Future<_i8.FileSystemEntity>.value(_FakeFileSystemEntity_8(
          this,
          Invocation.method(
            #delete,
            [],
            {#recursive: recursive},
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i8.FileSystemEntity>.value(_FakeFileSystemEntity_8(
          this,
          Invocation.method(
            #delete,
            [],
            {#recursive: recursive},
          ),
        )),
      ) as _i10.Future<_i8.FileSystemEntity>);
  @override
  _i10.Future<bool> exists() => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  bool existsSync() => (super.noSuchMethod(
        Invocation.method(
          #existsSync,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i10.Future<String> resolveSymbolicLinks() => (super.noSuchMethod(
        Invocation.method(
          #resolveSymbolicLinks,
          [],
        ),
        returnValue: _i10.Future<String>.value(''),
        returnValueForMissingStub: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  String resolveSymbolicLinksSync() => (super.noSuchMethod(
        Invocation.method(
          #resolveSymbolicLinksSync,
          [],
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i10.Future<_i6.FileStat> stat() => (super.noSuchMethod(
        Invocation.method(
          #stat,
          [],
        ),
        returnValue: _i10.Future<_i6.FileStat>.value(_FakeFileStat_4(
          this,
          Invocation.method(
            #stat,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i6.FileStat>.value(_FakeFileStat_4(
          this,
          Invocation.method(
            #stat,
            [],
          ),
        )),
      ) as _i10.Future<_i6.FileStat>);
  @override
  _i6.FileStat statSync() => (super.noSuchMethod(
        Invocation.method(
          #statSync,
          [],
        ),
        returnValue: _FakeFileStat_4(
          this,
          Invocation.method(
            #statSync,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeFileStat_4(
          this,
          Invocation.method(
            #statSync,
            [],
          ),
        ),
      ) as _i6.FileStat);
  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
        Invocation.method(
          #deleteSync,
          [],
          {#recursive: recursive},
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Stream<_i6.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {
            #events: events,
            #recursive: recursive,
          },
        ),
        returnValue: _i10.Stream<_i6.FileSystemEvent>.empty(),
        returnValueForMissingStub: _i10.Stream<_i6.FileSystemEvent>.empty(),
      ) as _i10.Stream<_i6.FileSystemEvent>);
  @override
  void createSync({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #createSync,
          [],
          {
            #recursive: recursive,
            #exclusive: exclusive,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<int> length() => (super.noSuchMethod(
        Invocation.method(
          #length,
          [],
        ),
        returnValue: _i10.Future<int>.value(0),
        returnValueForMissingStub: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);
  @override
  int lengthSync() => (super.noSuchMethod(
        Invocation.method(
          #lengthSync,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  _i10.Future<DateTime> lastAccessed() => (super.noSuchMethod(
        Invocation.method(
          #lastAccessed,
          [],
        ),
        returnValue: _i10.Future<DateTime>.value(_FakeDateTime_9(
          this,
          Invocation.method(
            #lastAccessed,
            [],
          ),
        )),
        returnValueForMissingStub: _i10.Future<DateTime>.value(_FakeDateTime_9(
          this,
          Invocation.method(
            #lastAccessed,
            [],
          ),
        )),
      ) as _i10.Future<DateTime>);
  @override
  DateTime lastAccessedSync() => (super.noSuchMethod(
        Invocation.method(
          #lastAccessedSync,
          [],
        ),
        returnValue: _FakeDateTime_9(
          this,
          Invocation.method(
            #lastAccessedSync,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDateTime_9(
          this,
          Invocation.method(
            #lastAccessedSync,
            [],
          ),
        ),
      ) as DateTime);
  @override
  _i10.Future<dynamic> setLastAccessed(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setLastAccessed,
          [time],
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);
  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setLastAccessedSync,
          [time],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<DateTime> lastModified() => (super.noSuchMethod(
        Invocation.method(
          #lastModified,
          [],
        ),
        returnValue: _i10.Future<DateTime>.value(_FakeDateTime_9(
          this,
          Invocation.method(
            #lastModified,
            [],
          ),
        )),
        returnValueForMissingStub: _i10.Future<DateTime>.value(_FakeDateTime_9(
          this,
          Invocation.method(
            #lastModified,
            [],
          ),
        )),
      ) as _i10.Future<DateTime>);
  @override
  DateTime lastModifiedSync() => (super.noSuchMethod(
        Invocation.method(
          #lastModifiedSync,
          [],
        ),
        returnValue: _FakeDateTime_9(
          this,
          Invocation.method(
            #lastModifiedSync,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDateTime_9(
          this,
          Invocation.method(
            #lastModifiedSync,
            [],
          ),
        ),
      ) as DateTime);
  @override
  _i10.Future<dynamic> setLastModified(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setLastModified,
          [time],
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);
  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setLastModifiedSync,
          [time],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<_i6.RandomAccessFile> open(
          {_i6.FileMode? mode = _i6.FileMode.read}) =>
      (super.noSuchMethod(
        Invocation.method(
          #open,
          [],
          {#mode: mode},
        ),
        returnValue:
            _i10.Future<_i6.RandomAccessFile>.value(_FakeRandomAccessFile_10(
          this,
          Invocation.method(
            #open,
            [],
            {#mode: mode},
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i6.RandomAccessFile>.value(_FakeRandomAccessFile_10(
          this,
          Invocation.method(
            #open,
            [],
            {#mode: mode},
          ),
        )),
      ) as _i10.Future<_i6.RandomAccessFile>);
  @override
  _i6.RandomAccessFile openSync({_i6.FileMode? mode = _i6.FileMode.read}) =>
      (super.noSuchMethod(
        Invocation.method(
          #openSync,
          [],
          {#mode: mode},
        ),
        returnValue: _FakeRandomAccessFile_10(
          this,
          Invocation.method(
            #openSync,
            [],
            {#mode: mode},
          ),
        ),
        returnValueForMissingStub: _FakeRandomAccessFile_10(
          this,
          Invocation.method(
            #openSync,
            [],
            {#mode: mode},
          ),
        ),
      ) as _i6.RandomAccessFile);
  @override
  _i10.Stream<List<int>> openRead([
    int? start,
    int? end,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #openRead,
          [
            start,
            end,
          ],
        ),
        returnValue: _i10.Stream<List<int>>.empty(),
        returnValueForMissingStub: _i10.Stream<List<int>>.empty(),
      ) as _i10.Stream<List<int>>);
  @override
  _i6.IOSink openWrite({
    _i6.FileMode? mode = _i6.FileMode.write,
    _i9.Encoding? encoding = const _i9.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openWrite,
          [],
          {
            #mode: mode,
            #encoding: encoding,
          },
        ),
        returnValue: _FakeIOSink_11(
          this,
          Invocation.method(
            #openWrite,
            [],
            {
              #mode: mode,
              #encoding: encoding,
            },
          ),
        ),
        returnValueForMissingStub: _FakeIOSink_11(
          this,
          Invocation.method(
            #openWrite,
            [],
            {
              #mode: mode,
              #encoding: encoding,
            },
          ),
        ),
      ) as _i6.IOSink);
  @override
  _i10.Future<_i11.Uint8List> readAsBytes() => (super.noSuchMethod(
        Invocation.method(
          #readAsBytes,
          [],
        ),
        returnValue: _i10.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
        returnValueForMissingStub:
            _i10.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
      ) as _i10.Future<_i11.Uint8List>);
  @override
  _i11.Uint8List readAsBytesSync() => (super.noSuchMethod(
        Invocation.method(
          #readAsBytesSync,
          [],
        ),
        returnValue: _i11.Uint8List(0),
        returnValueForMissingStub: _i11.Uint8List(0),
      ) as _i11.Uint8List);
  @override
  _i10.Future<String> readAsString(
          {_i9.Encoding? encoding = const _i9.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsString,
          [],
          {#encoding: encoding},
        ),
        returnValue: _i10.Future<String>.value(''),
        returnValueForMissingStub: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  String readAsStringSync({_i9.Encoding? encoding = const _i9.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsStringSync,
          [],
          {#encoding: encoding},
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i10.Future<List<String>> readAsLines(
          {_i9.Encoding? encoding = const _i9.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsLines,
          [],
          {#encoding: encoding},
        ),
        returnValue: _i10.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i10.Future<List<String>>.value(<String>[]),
      ) as _i10.Future<List<String>>);
  @override
  List<String> readAsLinesSync(
          {_i9.Encoding? encoding = const _i9.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsLinesSync,
          [],
          {#encoding: encoding},
        ),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);
  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i6.FileMode? mode = _i6.FileMode.write,
    bool? flush = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeAsBytesSync,
          [bytes],
          {
            #mode: mode,
            #flush: flush,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeAsStringSync(
    String? contents, {
    _i6.FileMode? mode = _i6.FileMode.write,
    _i9.Encoding? encoding = const _i9.Utf8Codec(),
    bool? flush = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeAsStringSync,
          [contents],
          {
            #mode: mode,
            #encoding: encoding,
            #flush: flush,
          },
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IOSink].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOSink extends _i1.Mock implements _i6.IOSink {
  @override
  _i9.Encoding get encoding => (super.noSuchMethod(
        Invocation.getter(#encoding),
        returnValue: _FakeEncoding_12(
          this,
          Invocation.getter(#encoding),
        ),
        returnValueForMissingStub: _FakeEncoding_12(
          this,
          Invocation.getter(#encoding),
        ),
      ) as _i9.Encoding);
  @override
  set encoding(_i9.Encoding? _encoding) => super.noSuchMethod(
        Invocation.setter(
          #encoding,
          _encoding,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<dynamic> get done => (super.noSuchMethod(
        Invocation.getter(#done),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);
  @override
  void add(List<int>? data) => super.noSuchMethod(
        Invocation.method(
          #add,
          [data],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void write(Object? object) => super.noSuchMethod(
        Invocation.method(
          #write,
          [object],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeAll(
    Iterable<dynamic>? objects, [
    String? separator = r'',
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #writeAll,
          [
            objects,
            separator,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeln([Object? object = r'']) => super.noSuchMethod(
        Invocation.method(
          #writeln,
          [object],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeCharCode(int? charCode) => super.noSuchMethod(
        Invocation.method(
          #writeCharCode,
          [charCode],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<dynamic> addStream(_i10.Stream<List<int>>? stream) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStream,
          [stream],
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);
  @override
  _i10.Future<dynamic> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);
  @override
  _i10.Future<dynamic> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);
}
